[package]
name = "holiday_jp"
version = "0.2.0"
authors = ["camelmasa <camelmasa@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
yaml-rust = "0.4.5"
time = { version = "0.3.17", features = ["macros", "parsing", "formatting"] }

[lib]
name = "holiday_jp"
path = "./src/lib.rs"
